# 公共配置yml文件
spring:
  profiles:
    active: prod
  application:
    name: user_center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hjy
    url: jdbc:mysql://localhost:3306/louis
  #超时  session 失效时间一天
  session:
    timeout: 86400
# ??mybatisplus????????????
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: idDelete # ????????????(since 3.3.0,????????????2)
      logic-delete-value: 1 # ??????(??? 1)
      logic-not-delete-value: 0 # ??????(??? 0)
server:
  port: 8080
  servlet:
    context-path: /api
